package com.utorresa.biblioteca.models.entities;
import lombok.Data;
import java.time.LocalDate;
import jakarta.persistence.Column;

import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

@Data
@Entity
@Table(name = "book")
public class Book {
    @Id
    @jakarta.persistence.GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(name = "tittle", nullable = false)   
    private String title;
    @Column(name = "author", nullable = false)
    private String author;
    @Column(name = "isbn", nullable = false, unique = true)
    private String isbn;
    @Column(name = "genre", nullable = false)
    private String genre;
    @Column(name = "year_published", nullable = false)
    private LocalDate PublishedDate;
    @Column(name = "status", nullable = false)
    @Enumerated(EnumType.STRING)
    private Status status;
    public enum Status {
        AVAILABLE,
        BORROWED,
        RESERVED
    }

    // Constructors, getters, and setters can be generated by Lombok

}
